<?php
/** @var Klaviyo\Reclaim\Block\Catalog\Product\ViewedProduct $block */
?>

<script text="text/javascript">
    document.addEventListener("DOMContentLoaded", function() {
        var _learnq = _learnq || [];
        _learnq.push(['track', 'Viewed Product', <?= $block->getViewedProductJson() ?>]);
        _learnq.push(['trackViewedItem', <?= $block->getViewedItemJson() ?>]);
    });
</script>

