<?php if ($block->isKlaviyoEnabled() && $block->getPublicApiKey()): ?>
    <script>
        require([
           'jquery',
           'mage/url'
        ], function (jQuery, url) {
          url.setBaseUrl('<?= $block->escapeJs($block->escapeUrl($block->getBaseUrl())) ?>');
          jQuery.ajax({
              url: url.build('reclaim/checkout/reload'),
              method: 'POST',
              data: {}
          });
        });
    </script>
<?php endif; ?>
