<?php $klaviyoKey = $block->getPublicApiKey(); ?>
<?php if ( $block->isKlaviyoEnabled() && $klaviyoKey ): ?>
<script type="application/javascript" async 
 src="https://static.klaviyo.com/onsite/js/klaviyo.js?company_id=<?= $klaviyoKey; ?>"></script>

    <script type="text/x-magento-init">
        {
            "*": {
                "KlaviyoCustomerData": {}
            }
        }
    </script>
<?php endif; ?>
