<?php $klaviyoKey = $this->getPublicApiKey(); ?>
<?php if ( $this->isKlaviyoEnabled() && $klaviyoKey ): ?>
<script type="application/javascript" async 
 src="https://static.klaviyo.com/onsite/js/klaviyo.js?company_id=<?php echo $klaviyoKey; ?>"></script>

    <script type="text/x-magento-init">
        {
            "*": {
                "KlaviyoCustomerData": {}
            }
        }
    </script>
<?php endif; ?>
