name: Stable Release
run-name: "Stable Release for ${{ github.ref_name }}"
on:
  push:
    branches:
      - 'stable/**'

jobs:
  determine-if-deploy:
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ steps.tag_exists.outputs.exists  == 'false' }}
      version: ${{ steps.latest_version.outputs.version }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4.4.0
      with:
        python-version: "3.11"
    - name: Install Changelogger
      run: pip install changelogged==0.11.3
    - name: Get Latest Version
      id: latest_version
      run: |
        VERSION=$(changelogger versions --latest)
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
    - uses: mukunku/tag-exists-action@v1.2.0
      id: tag_exists
      with:
        tag: ${{ steps.latest_version.outputs.version }}

  get-stable-tag:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: determine-if-deploy
    if: needs.determine-if-deploy.outputs.deploy == 'true'
    outputs:
      version: ${{ steps.bump_version.outputs.version || steps.init_version.outputs.version }}
    steps:
    - name: Extract Branch Version
      shell: bash
      run: |
        # Strip the `stable/` prefix and the `x` suffix from the current
        # release branch
        VERSION_PREFIX=$(echo "${GITHUB_REF#refs/heads/}" | sed -e "s/^stable\///" -e "s/x//")
        echo "version_prefix=${VERSION_PREFIX}" >> $GITHUB_OUTPUT
      id: extract_version_prefix

    - name: Find Latest Version
      uses: oprypin/find-latest-tag@v1
      with:
        repository: ${{ github.repository }}
        prefix: ${{ steps.extract_version_prefix.outputs.version_prefix }}
      id: latest_patch

    - name: Bump Patch Version
      run: |
        VERSION=$(echo ${{ steps.latest_patch.outputs.tag }} | awk -F. '/[0-9]+\./{$NF++;print}' OFS=.)
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
      id: bump_version

    - name: Initial Release
      if: failure()
      run: |
        # Version prefix is in the format `x.y.`, so we need to append a `0`
        # to the end
        echo "version=${{ steps.extract_version_prefix.outputs.version_prefix }}0" >> $GITHUB_OUTPUT
      id: init_version

  github-tag-and-release:
    runs-on: ubuntu-latest
    needs: [determine-if-deploy, get-stable-tag]
    if: needs.determine-if-deploy.outputs.version == needs.get-stable-tag.outputs.version
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python 3.11
      uses: actions/setup-python@v4.4.0
      with:
        python-version: '3.11'

    - name: Install Changelogger
      run: pip install changelogged==0.11.3

    - name: Get Changelog Contents
      id: changelog
      run: |
        DELIMITER=$(openssl rand -base64 12)
        VERSION=${{ needs.determine-if-deploy.outputs.version }}
        # Need to capture multiline output in env to preserve newlines
        echo "content<<${DELIMITER}" >> $GITHUB_ENV
        # Add changelog content to the env for release notes
        changelogger notes $VERSION --no-pretty >> $GITHUB_ENV
        echo ${DELIMITER} >> $GITHUB_ENV

    - name: Create GitHub Tag & Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ needs.determine-if-deploy.outputs.version }}
        commit: ${{ github.sha }}
        name: Release ${{ needs.determine-if-deploy.outputs.version }}
        body: ${{ env.content }}
        prerelease: true

    - name: Send PagerDuty alert on failure
      if: ${{ failure() }}
      uses: award28/action-pagerduty-alert@0.4.0
      with:
        pagerduty-integration-key: '${{ secrets.PAGERDUTY_INTEGRATION_KEY }}'
        pagerduty-dedup-key: magneto_two_cd

  integration-release:
    runs-on: ubuntu-latest
    needs: [determine-if-deploy, github-tag-and-release]
    steps:
    - run: echo "Releasing to Magento2"
    - name: Send PagerDuty alert on failure
      if: ${{ failure() }}
      uses: award28/action-pagerduty-alert@0.4.0
      with:
        pagerduty-integration-key: '${{ secrets.PAGERDUTY_INTEGRATION_KEY }}'
        pagerduty-dedup-key: magento_two_cd
